---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-lab13
spec:
  selector:
    matchLabels:
      app: netology-lab13
  replicas: 2
  template:
    metadata:
      labels:
        app: netology-lab13
    spec:
      containers:
      - name: netology-lab13
        image: docker.io/alexspedan/netologyfrontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "news" 
      - name: frontendtest
        image: docker.io/alexspedan/netologybackend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "news"
